---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pttg-ip-smoke-tests
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pttg-ip-smoke-tests
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: pttg-ip-smoke-tests
        version: {{.VERSION}}
    spec:
      imagePullSecrets:
        - name: registrykey
      initContainers:
        - name: truststore
          image: quay.io/ukhomeofficedigital/cfssl-sidekick-jks:v0.0.7
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          args:
            - --certs=/certs
            - --command=/usr/bin/create-keystore.sh /certs/tls.pem /certs/tls-key.pem /etc/ssl/certs/acp-root.crt
            - --domain=pttg-ip-smoke-tests.${KUBE_NAMESPACE}.svc.cluster.local
            - --domain=localhost
            - --onetime=true
          env:
          - name: KUBE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          volumeMounts:
          - name: certs
            mountPath: /certs
          - name: keystore
            mountPath: /etc/keystore
          - name: bundle
            mountPath: /etc/ssl/certs
            readOnly: true
      containers:
        - name: pttg-ip-smoke-tests
          image: quay.io/ukhomeofficedigital/pttg-ip-smoke-tests:{{.VERSION}}
          resources:
            limits:
              cpu: 1600m
              memory: 1224Mi
            requests:
              cpu: 100m
              memory: 968Mi
          env:
            - name: IPS_ENDPOINT
              value: https://pttg-ip-api.{{.KUBE_NAMESPACE}}.svc.cluster.local/incomeproving/v3/individual/financialstatus
            - name: IPS_BASICAUTH
              valueFrom:
                secretKeyRef:
                  name: pttg-ip-api-service-secrets
                  key: pttg_ip_smoke_tests
            - name: JAVA_OPTS
              value: '-Xms150m -Xmx250m -Djavax.net.ssl.trustStore=/etc/keystore/truststore.jks'
            - name: JDK_TRUST_FILE
              value: '/etc/keystore/truststore.jks'
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /etc/keystore
              name: keystore
              readOnly: true
      volumes:
        - name: keystore
          emptyDir:
            medium: "Memory"
        - name: certs
          emptyDir:
            medium: "Memory"
        - name: bundle
          configMap:
            name: bundle
