---
apiVersion: batch/v1
kind: Job
metadata:
  name: pttg-ip-smoke-tests
  labels:
    version: {{.VERSION}}
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: pttg-ip-smoke-tests
        image: quay.io/ukhomeofficedigital/pttg-ip-smoke-tests:{{.VERSION}}
      restartPolicy: Never
