---
apiVersion: batch/v1
kind: Job
metadata:
  name: pttg-ip-smoke-tests
  labels:
    version: latest
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: pttg-ip-smoke-tests
        image: quay.io/ukhomeofficedigital/pttg-ip-smoke-tests:latest
        resources:
          limits:
            cpu: 1600m
            memory: 1224Mi
          requests:
            cpu: 100m
            memory: 968Mi
        env:
          name: IP_API_ROOT_URL
          value: https://pttg-ip-api.{{.KUBE_NAMESPACE}}.svc.cluster.local
      restartPolicy: Never
