---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-ip-smoke-tests
  name: pttg-ip-smoke-tests
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: pttg-ip-smoke-tests
